version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/rabu-dev/Sistema-de-aceso-a-datos-/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          java main

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name